export enum TxType {
  claimRewards = 'claimRewards',
  createGarden = 'createGarden',
  deleteCandidate = 'deleteCandidate',
  deposit = 'deposit',
  sendInvites = 'sendInvites',
  submitStrategy = 'submitStrategy',
  submitVotes = 'submitVotes',
  updateStrategyExit = 'updateStrategyExit',
  stakeProphet = 'stakeProphet',
  withdraw = 'withdraw',
  bond = 'bond',
  mintGardenNft = 'mintGardenNft',
  default = 'default',
}
