module.exports = {
  BabController: 'BabControllerV17',
  BabControllerLocal: 'BabController',
  BabControllerProxy: 'BabControllerProxy',
  BABLToken: 'BABLToken',
  Viewer: 'IViewer',
  IERC721Enumerable: 'IERC721Enumerable',
  Garden: 'IGarden',
  GardenNFT: 'GardenNFT',
  GardenValuer: 'GardenValuer',
  Heart: 'Heart',
  IERC20: 'IERC20',
  MardukGate: 'MardukGate',
  ProphetsArrival: 'ProphetsArrival',
  RewardsDistributor: 'RewardsDistributor',
  Strategy: 'Strategy',
  StrategyNFT: 'StrategyNFT',
  TimeLockRegistry: 'TimeLockRegistry',
  UniswapPoolIntegration: 'UniswapPoolIntegration',
  YearnVaultIntegration: 'YearnVaultIntegration',
};
