export const Routes = {
  index: '/',
  creatorLander: '/managers',
  daoLander: '/daos',
  admin: '/admin',
  explore: '/explore',
  garden: '/garden/:gardenAddress',
  leaderboard: '/leaderboard',
  me: '/me',
  heart: '/heart',
  portfolio: '/portfolio',
  privacy: '/privacy',
  prophetMint: '/prophets/mint',
  prophetPortfolio: '/prophets/portfolio',
  prophetProfile: '/prophets/gallery/:id',
  prophets: '/prophets',
  prophetsGallery: '/prophets/gallery',
  seed: '/seed',
  terms: '/terms',
};

export const RoutesExternal = {
  babylonOrigin: 'https://www.youtube.com/watch?v=Cn-GKRwB9wc',
  coingecko: 'https://www.coingecko.com/en/coins/babylon-finance',
  coinmarketcap: 'https://coinmarketcap.com/currencies/babylon-finance/',
  docs: 'https://docs.babylon.finance',
  docsIntegrations: 'https://docs.babylon.finance/protocol/integrations',
  etherscan: 'https://etherscan.io/token/0xF4Dc48D260C93ad6a96c5Ce563E70CA578987c74',
  gaslessTx: 'https://docs.babylon.finance/getting-started/faq#what-is-a-signature-gasless-based-transaction',
  gardenExplainer: 'https://www.youtube.com/watch?v=xEDvGE8aBxM',
  heartPost: 'https://medium.com/babylon-finance/the-heart-of-babylon-defi-3-0-6d16e35817f2',
  messariProfile: 'https://messari.io/asset/babylon-finance',
  openseaProphets: 'https://opensea.io/collection/babylon-prophets',
  profitRewardScale: 'https://docs.babylon.finance/babl/mining#negative-break-even-and-positive-strategies',
  tokenomics: 'https://docs.babylon.finance/babl/tokenomics',
  uniswapPool: 'https://info.uniswap.org/#/tokens/0xf4dc48d260c93ad6a96c5ce563e70ca578987c74',
  audits: 'https://github.com/babylon-finance/security/tree/main/audits',
  bounties: 'https://immunefi.com/bounty/babylonfinance/',
};
