export enum Tab {
  ACTIVE = 'active',
  CANDIDATE = 'candidate',
  COMPLETED = 'completed',
  CREATE_GARDEN = 'create_garden',
  GARDEN_PROPERTIES = 'garden_properties',
  GARDEN_THESIS = 'garden_thesis',
  GARDEN_HOF = 'garden_hof',
  EDIT = 'edit',
  EXPLORE = 'explore',
  GARDENS = 'gardens',
  INVITES = 'invites',
  LEADERBOARD = 'leaderboard',
  MEMBERS = 'members',
  PERFORMANCE = 'performance',
  PORTFOLIO = 'portfolio',
  PREVIEW = 'preview',
  STRATEGIES = 'strategies',
  STRATEGISTS = 'strategists',
  SUBMIT_STRATEGY = 'submit_strategy',
  USER = 'user',
}
